#!/bin/bash

#complete -W "$(./bench list) ./bench

ROOT_DIR="$(dirname $0)"

usage()
{
    echo -ne \
        "\nUsage:" \
        "\n    $(basename $0) <server|client|bulk|report> [help]" \
        "\n    $(basename $0) <server|client|bulk|report> <args>..." \
        "\n\n"
}

case "$1" in
    server)  shift; $ROOT_DIR/bin/bench-server "$@";;
    client)  shift; $ROOT_DIR/bin/bench-client "$@";;
    bulk)    shift; $ROOT_DIR/bin/bench-bulk "$@";;
    report)  shift; $ROOT_DIR/bin/bench-report "$@";;
    list)    echo "server client help";;
    compgen) echo "complete -W \"$($0 list)\" $0";;
    ""|help) usage;;
    *) { echo "unknown type $1"; usage; exit 1; } >&2;;
esac
