#!/usr/bin/groovy

// load pipeline functions
// Requires pipeline-github-lib plugin to load library from github
@Library('github.com/vialogi/ci-demo@simpl_cred_string_support')
def matrix = new com.mellanox.cicd.Matrix()

matrix.main()
