#!/usr/bin/env python3

# Mapping of XLIO configuration keys to their corresponding environment variables
# For mappings that are not specified in the schema, an empty string is used

config_mapping = {
    # core section
    "core.resources.memory_limit": "XLIO_MEMORY_LIMIT",
    "core.resources.hugepages.enable": "XLIO_MEM_ALLOC_TYPE",
    "core.resources.hugepages.size": "XLIO_HUGEPAGE_SIZE",
    "core.resources.external_memory_limit": "XLIO_MEMORY_LIMIT_USER",
    "core.resources.heap_metadata_block_size": "XLIO_HEAP_METADATA_BLOCK",
    "core.quick_init": "XLIO_QUICK_START",
    "core.exception_handling.mode": "XLIO_EXCEPTION_HANDLING",
    "core.signals.sigint.exit": "XLIO_HANDLE_SIGINTR",
    "core.signals.sigsegv.backtrace": "XLIO_HANDLE_SIGSEGV",
    "core.syscall.dup2_support": "XLIO_CLOSE_ON_DUP2",
    "core.syscall.fork_support": "XLIO_FORK",
    "core.syscall.getsockname_dummy_send": "XLIO_TRIGGER_DUMMY_SEND_GETSOCKNAME",
    "core.syscall.deferred_close": "XLIO_DEFERRED_CLOSE",
    "core.syscall.allow_privileged_sockopt": "XLIO_ALLOW_PRIVILEGED_SOCK_OPT",
    "core.syscall.enable_sysctl": "XLIO_AVOID_SYS_CALLS_ON_TCP_FD",
    
    # network section
    "network.protocols.ip.mtu": "XLIO_MTU",
    "network.timing.ts_conversion": "XLIO_HW_TS_CONVERSION",
    "network.protocols.tcp.performance.wmem": "XLIO_TCP_SEND_BUFFER_SIZE",
    "network.protocols.tcp.performance.nodelay.enable": "XLIO_TCP_NODELAY",
    "network.protocols.tcp.performance.nodelay.byte_threshold": "XLIO_TCP_NODELAY_TRESHOLD",
    "network.protocols.tcp.performance.quickack": "XLIO_TCP_QUICKACK",
    "network.protocols.tcp.performance.push": "XLIO_TCP_PUSH_FLAG",
    "network.protocols.tcp.performance.linger_0": "XLIO_TCP_ABORT_ON_CLOSE",
    "network.protocols.tcp.congestion_control": "XLIO_TCP_CC_ALGO",
    "network.protocols.tcp.max_syn_rate": "XLIO_TCP_MAX_SYN_RATE",
    "network.protocols.tcp.timestamps": "XLIO_TCP_TIMESTAMP_OPTION",
    "network.protocols.tcp.timer_msec": "XLIO_TCP_TIMER_RESOLUTION_MSEC",
    "network.protocols.tcp.mss": "XLIO_MSS",
    "network.protocols.udp.performance.batch_size": "TX_BUFS_BATCH_UDP",
    "network.multicast.mc_loopback": "XLIO_TX_MC_LOOPBACK",
    "network.multicast.mc_flowtag_acceleration": "XLIO_MC_FORCE_FLOWTAG",
    "network.multicast.mc_disable_flowtag": "XLIO_DISABLE_FLOW_TAG",
    "network.multicast.wait_after_join_msec": "XLIO_WAIT_AFTER_JOIN_MSEC",
    "network.neighbor.update_interval_msec": "XLIO_NETLINK_TIMER",
    "network.neighbor.uc_arp_retries": "XLIO_NEIGH_UC_ARP_QUATA",
    "network.neighbor.uc_arp_delay_msec": "XLIO_NEIGH_UC_ARP_DELAY_MSEC",
    "network.neighbor.errors_before_reset": "XLIO_NEIGH_NUM_ERR_RETRIES",
    "network.packet_processing.max_gro_streams": "XLIO_GRO_STREAMS_MAX",
    
    # hardware_features section
    "hardware_features.tcp.striding_rq.enable": "XLIO_STRQ",
    "hardware_features.tcp.striding_rq.strides": "XLIO_STRQ_NUM_STRIDES",
    "hardware_features.tcp.striding_rq.stride_size": "XLIO_STRQ_STRIDE_SIZE_BYTES",
    "hardware_features.tcp.striding_rq.spare_strides": "XLIO_STRQ_STRIDES_COMPENSATION_LEVEL",
    "hardware_features.tcp.lro": "XLIO_LRO",
    "hardware_features.tcp.rules.2t_rules": "XLIO_TCP_2T_RULES",
    "hardware_features.tcp.rules.3t_rules": "XLIO_TCP_3T_RULES",
    "hardware_features.tcp.tso.enable": "XLIO_TSO",
    "hardware_features.tcp.tso.max_size": "XLIO_TSO_MAX_SIZE",
    "hardware_features.tcp.tls_offload.tx_enable": "XLIO_UTLS_TX",
    "hardware_features.tcp.tls_offload.rx_enable": "XLIO_UTLS_RX",
    "hardware_features.tcp.tls_offload.dek_cache_max_size": "XLIO_HIGH_WMARK_DEK_CACHE_SIZE",
    "hardware_features.tcp.tls_offload.dek_cache_min_size": "XLIO_LOW_WMARK_DEK_CACHE_SIZE",
    "hardware_features.udp.rules.3t_rules": "XLIO_UDP_3T_RULES",
    "hardware_features.udp.rules.only_mc_l2_rules": "XLIO_ETH_MC_L2_ONLY_RULES",
    
    # performance section
    "performance.rings.max_per_interface": "XLIO_RING_LIMIT_PER_INTERFACE",
    "performance.rings.tx.alloc_logic": "XLIO_RING_ALLOCATION_LOGIC_TX",
    "performance.rings.tx.migration_ratio": "XLIO_RING_MIGRATION_RATIO_TX",
    "performance.rings.tx.max_on_device_memory": "XLIO_RING_DEV_MEM_TX",
    "performance.rings.rx.alloc_logic": "XLIO_RING_ALLOCATION_LOGIC_RX",
    "performance.rings.rx.migration_ratio": "XLIO_RING_MIGRATION_RATIO_RX",
    "performance.threading.mutex_over_spinlock": "XLIO_MULTILOCK",
    "performance.threading.cpu_affinity": "XLIO_INTERNAL_THREAD_AFFINITY",
    "performance.threading.cpuset": "XLIO_INTERNAL_THREAD_CPUSET",
    "performance.threading.handlers.timer_msec": "XLIO_TIMER_RESOLUTION_MSEC",
    "performance.threading.handlers.behavior": "XLIO_TCP_CTL_THREAD",
    "performance.polling.rx_poll_on_tx": "XLIO_RX_POLL_ON_TX_TCP",
    "performance.polling.skip_cq_on_rx": "XLIO_SKIP_POLL_IN_RX",
    "performance.polling.rx_cq_wait_ctrl": "XLIO_RX_CQ_WAIT_CTRL",
    "performance.polling.rx_duration_usec": "XLIO_RX_POLL",
    "performance.polling.select.poll_usec": "XLIO_SELECT_POLL",
    "performance.polling.select.poll_os_force": "XLIO_SELECT_POLL_OS_FORCE",
    "performance.polling.select.poll_os_ratio": "XLIO_SELECT_POLL_OS_RATIO",
    "performance.polling.select.skip_os": "XLIO_SELECT_SKIP_OS",
    "performance.polling.kernel_fd_attention_level": "XLIO_RING_KERNEL_FD_ATTENTION_LEVEL",
    "performance.polling.rx_buffer_max_count": "XLIO_CQ_POLL_BATCH_MAX",
    "performance.polling.rx_kernel_fd_attention_level": "XLIO_RX_UDP_POLL_OS_RATIO",
    "performance.polling.yield_on_poll": "XLIO_RX_POLL_YIELD",
    "performance.polling.offload_transition_poll_count": "XLIO_RX_POLL_INIT",
    "performance.completion_queue.interrupt_per_packet": "XLIO_INTERNAL_THREAD_ARM_CQ",
    "performance.completion_queue.keep_full": "XLIO_CQ_KEEP_QP_FULL",
    "performance.completion_queue.periodic_drain_msec": "XLIO_PROGRESS_ENGINE_INTERVAL",
    "performance.completion_queue.periodic_drain_max_cqes": "XLIO_PROGRESS_ENGINE_WCE_MAX",
    "performance.completion_queue.rx_drain_rate_nsec": "XLIO_RX_CQ_DRAIN_RATE_NSEC",
    "performance.completion_queue.interrupt_moderation.enable": "XLIO_CQ_MODERATION_ENABLE",
    "performance.completion_queue.interrupt_moderation.packet_count": "XLIO_CQ_MODERATION_COUNT",
    "performance.completion_queue.interrupt_moderation.period_usec": "XLIO_CQ_MODERATION_PERIOD_USEC",
    "performance.completion_queue.interrupt_moderation.adaptive_count": "XLIO_CQ_AIM_MAX_COUNT",
    "performance.completion_queue.interrupt_moderation.adaptive_period_usec": "XLIO_CQ_AIM_MAX_PERIOD_USEC",
    "performance.completion_queue.interrupt_moderation.adaptive_change_frequency_msec": "XLIO_CQ_AIM_INTERVAL_MSEC",
    "performance.completion_queue.interrupt_moderation.interrupt_per_sec": "XLIO_CQ_AIM_INTERRUPTS_RATE_PER_SEC",
    "performance.completion_queue.rx_spare_buffers": "XLIO_QP_COMPENSATION_LEVEL",
    "performance.buffers.batching_mode": "XLIO_BUFFER_BATCHING_MODE",
    "performance.buffers.tx.buf_size": "XLIO_TX_BUF_SIZE",
    "performance.buffers.tx.tcp_batch_size": "XLIO_TX_BUFS_BATCH_TCP",
    "performance.buffers.tx.global_array_size": "XLIO_TX_BUFS",
    "performance.buffers.tx.prefetch_size": "XLIO_TX_PREFETCH_BYTES",
    "performance.buffers.tx.nonblocking_eagain": "XLIO_TX_NONBLOCKED_EAGAINS",
    "performance.buffers.rx.buf_size": "XLIO_RX_BUF_SIZE",
    "performance.buffers.rx.global_array_size": "XLIO_RX_BUFS",
    "performance.buffers.rx.override_rcvbuf_limit": "XLIO_RX_BYTES_MIN",
    "performance.buffers.rx.tcp_batch_size": "RX_BUFS_BATCH",
    "performance.buffers.rx.prefetch_size": "XLIO_RX_PREFETCH_BYTES",
    "performance.buffers.rx.prefetch_before_poll": "XLIO_RX_PREFETCH_BYTES_BEFORE_POLL",
    "performance.buffers.work_request_elements.tx_global_array_size": "XLIO_TX_WRE",
    "performance.buffers.work_request_elements.tx_completion_batch_size": "XLIO_TX_WRE_BATCHING",
    "performance.buffers.work_request_elements.tx_max_inline_size": "XLIO_TX_MAX_INLINE",
    "performance.buffers.work_request_elements.rx_global_array_size": "XLIO_RX_WRE",
    "performance.buffers.work_request_elements.rx_batch_size": "XLIO_RX_WRE_BATCHING",
    "performance.buffers.tcp_segments.socket_batch_size": "XLIO_TX_SEGS_BATCH_TCP",
    "performance.buffers.tcp_segments.ring_batch_size": "XLIO_TX_SEGS_RING_BATCH_TCP",
    "performance.buffers.tcp_segments.pool_batch_size": "XLIO_TX_SEGS_POOL_BATCH_TCP",
    
    # applications section
    "applications.api.socketextreme": "XLIO_SOCKETEXTREME",
    "applications.api.sendfile_limit": "XLIO_ZC_CACHE_THRESHOLD",
    "applications.api.hugepages.size": "XLIO_USER_HUGE_PAGE_SIZE",
    "applications.nginx.src_port_stride": "XLIO_NGINX_SRC_PORT_STRIDE",
    "applications.nginx.workers_num": "XLIO_NGINX_WORKERS_NUM",
    "applications.nginx.udp_pool_size": "XLIO_NGINX_UDP_POOL_SIZE",
    "applications.nginx.udp_socket_pool_reuse": "XLIO_NGINX_UDP_POOL_RX_NUM_BUFFS_REUSE",
    "applications.nginx.distribute_cq": "XLIO_DISTRIBUTE_CQ",
    "applications.profiles.spec": "XLIO_SPEC",
    "applications.acceleration_control.default_acceleration": "XLIO_OFFLOADED_SOCKETS",
    "applications.acceleration_control.app_id": "XLIO_APPLICATION_ID",
    
    # observability section
    "observability.log.level": "XLIO_TRACELEVEL",
    "observability.log.file_path": "XLIO_LOG_FILE",
    "observability.log.details": "XLIO_LOG_DETAILS",
    "observability.log.colors": "XLIO_LOG_COLORS",
    "observability.stats.file_path": "XLIO_STATS_FILE",
    "observability.stats.fd_num": "XLIO_STATS_FD_NUM",
    "observability.stats.shmem_dir": "XLIO_STATS_SHMEM_DIR",
    "observability.stats.cpu_usage": "XLIO_CPU_USAGE_STATS",
    "observability.exit_report": "XLIO_PRINT_REPORT",
    "observability.daemon.enable": "XLIO_SERVICE_ENABLE",
    "observability.daemon.dir": "XLIO_SERVICE_NOTIFY_DIR",
} 