#!/bin/bash

if systemctl >/dev/null 2>&1; then
    systemctl --no-reload disable xlio.service >/dev/null 2>&1 || true
    systemctl stop xlio.service || true
elif [ -e /sbin/chkconfig ]; then
    /etc/init.d/xlio stop || true
    /sbin/chkconfig --del xlio || true
elif [ -e /usr/sbin/update-rc.d ]; then
    /etc/init.d/xlio stop || true
    /usr/sbin/update-rc.d -f xlio remove || true
else
    /etc/init.d/xlio stop || true
    /usr/lib/lsb/remove_initd /etc/init.d/xlio || true
fi
