ARG ARCH=x86_64
ARG HARBOR_URL=nbu-harbor.gtm.nvidia.com
FROM $HARBOR_URL/hpcx/$ARCH/rhel8.6/core:latest as core
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME} && \
    mkdir /build && chown -R ${_LOGIN} /build

FROM core as cppcheck
ENV CPPCHECK_VERSION="2.17.1"
RUN yum install -y curl make gcc gcc-c++ sudo procps-ng autoconf \
    automake make libtool libnl3-devel libnl3 rdma-core-devel \
    rdma-core bc git \
 && yum clean all \
 && pushd /tmp \
 && curl -L -o "${CPPCHECK_VERSION}".tar.gz "https://github.com/danmar/cppcheck/archive/${CPPCHECK_VERSION}.tar.gz" \
 && tar xvf "$CPPCHECK_VERSION".tar.gz \
 && cd cppcheck-"$CPPCHECK_VERSION" \
 && make -j8 FILESDIR=/usr/share/cppcheck \
 && make install FILESDIR=/usr/share/cppcheck \
 && popd \
 && rm -rf /tmp/cppcheck-"$CPPCHECK_VERSION"* 
 ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]

FROM core as csbuild
ARG _LOGIN=swx-jenkins
RUN yum install -y yum-utils \
 && yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
 && yum --nogpgcheck install -y curl make gcc gcc-c++ \
 && yum install -y csbuild clang-tools-extra sudo autoconf automake libtool \
    libnl3-devel libnl3 rdma-core-devel rdma-core bc \
 && yum clean all

RUN pip3 install -U pip --no-cache-dir \
 && pip3 install compiledb --no-cache-dir

USER "$_LOGIN"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]


FROM core as release
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ARG WEBREPO_URL=webrepo.gtm.nvidia.com
RUN sed -i "s#http://webrepo#http://${WEBREPO_URL}#" /etc/yum.repos.d/* && \
    sed -i 's/mirrorlist/#mirrorlist/;s!#baseurl=http://mirror.centos.org!baseurl=http://vault.centos.org!' /etc/yum.repos.d/* && \
    echo "[mlnx-opt]" > /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 8.6 mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://${WEBREPO_URL}/RH/optional/8.6/x86_64/" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    yum makecache

RUN yum install --allowerasing -y \
    git autoconf automake libtool gcc \
    sudo gcc-c++ libibverbs-devel json-c-devel rdma-core \
    librdmacm unzip patch wget make \
    libnl3-devel rpm-build


FROM harbor.mellanox.com/hpcx/$ARCH/rhel8.6/base as build
RUN yum install -y json-c-devel


FROM core as bduck
ARG WEBREPO_URL=webrepo.gtm.nvidia.com
RUN sed -i "s/webrepo/${WEBREPO_URL}/" /etc/yum.repos.d/* && \
    yum install --allowerasing -y \
    jq git java-11-openjdk sudo && \
    yum clean all && \
    rm -rf /var/cache/yum
