ARG ARCH=aarch64
ARG HARBOR_URL=harbor.mellanox.com
FROM ${HARBOR_URL}/swx-infra/media/${ARCH}/base/oraclelinux:9.4

ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ARG WEBREPO_URL=webrepo.gtm.nvidia.com

RUN sed -i 's|\$WEBREPO_URL|'"${WEBREPO_URL}"'|g' /etc/yum.repos.d/*.repo && \
    yum clean all && \
    yum makecache

RUN yum install yum-utils \
 && yum-config-manager --add-repo https://dl.fedoraproject.org/pub/epel/9/Everything/aarch64/ \
 && yum install -y --nogpgcheck \
    autoconf automake make libtool git gcc-c++ libtool json-c-devel \
    clang rdma-core-devel openssl-devel glib2-devel libnl3-devel \
    python3-pip sudo rpm-build gtest-devel meson ninja-build \
    libzip-devel libpcap-devel jsoncpp-devel \
 && yum clean all \
 && rm -rf /var/cache/yum && rm -rf /var/cache/dnf

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME} && \
    mkdir /build && chown -R ${_LOGIN} /build

USER "$_LOGIN"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
