ARG ARCH=x86_64
ARG HARBOR_URL=nbu-harbor.gtm.nvidia.com
ARG OS_VERSION=9.6

FROM ${HARBOR_URL}/swx-infra/media/${ARCH}/base/rhel:${OS_VERSION} AS core
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME} && \
    mkdir /build && chown -R ${_LOGIN} /build


FROM core AS static

RUN dnf install -y dnf-utils \
 && dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
 && dnf install --allowerasing -y cppcheck csbuild clang-tools-extra sudo curl autoconf automake make libtool \
    libnl3-devel libnl3 rdma-core-devel rdma-core bc python3-pip \
 && dnf clean all \
 && rm -rf /var/cache/dnf

RUN pip3 install -U pip --no-cache-dir \
 && pip3 install compiledb --no-cache-dir


FROM core AS build

RUN dnf install --allowerasing -y json-c-devel curl \
    autoconf automake make libtool gcc-c++ rpm-build \
 && dnf clean all \
 && rm -rf /var/cache/dnf

# Install DOCA
COPY .ci/scripts/doca_install.sh /tmp/doca_install.sh
RUN chmod +x /tmp/doca_install.sh && \
    /tmp/doca_install.sh && \
    rm -f /tmp/doca_install.sh /tmp/GPG-KEY-Mellanox.pub
